---
title: "hw5"
author: "Keyi Wang"
date: "11/6/2019"
output: github_document
---

```{r setup, include=FALSE}
# knitr will run the chunk but not include the chunk in the final document
# copy from Jeff

# ensure reproductivity
set.seed(10)

library(tidyverse)
library(viridis)
library(ggridges)
library(patchwork)
library(rvest)

knitr::opts_chunk$set(
  # display the code in the code truck above its results in the final document
  echo = TRUE,
  # do not display any warning messages generated by the code
  warning = FALSE,
  # set the figure to be 8 x 6, and the proportion it takes to be 90%
  fig.width = 8,
  fig.height = 6, 
  out.width = "90%"
)

options(
  ggplot2.countinuous.colour = "viridis",
  ggplot2.countinuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

theme_set(theme_bw() + theme(legend.position = "bottom"))

```


## problem 1 
```{r}
set.seed(10)

iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species))

## writing function filling
  filling = function(vector) {
  if (!is.vector(vector)) {
    stop("Input should be a vector.")
  }
  if (is.numeric(vector)) {
    vector = vector %>% 
      replace_na(mean(vector[!is.na(vector)]))
  }  else if(is.character(vector)) {
    vector = vector %>% replace_na ("virginica")
  } 
  }
  iris_without_missing = map_df(.x = iris_with_missing, ~ filling(.x))
  iris_without_missing

```

## problem 2 
```{r message = FALSE}
## dataframe of all the datasets
total_dataset = list.files(path = "./data/", full.names = TRUE) %>% 
  as.data.frame() %>% 
  rename("file_id" = ".") %>% 
  mutate(file_id = as.character(file_id))

##Create a tidy dataframe containing data from all participants, including the subject ID, arm, and observations over time  
 tidy_data =  
 total_dataset %>% 
  mutate("data" = purrr::map(.x = pull(., file_id), read_csv),
         file_id = str_extract(file_id, "[conexp]{3}_[0-9]{2}")) %>%
  unnest() %>% 
    pivot_longer(
    names_prefix = "week_",
    cols = week_1:week_8,
    names_to = "week",
    values_to = "observations"
  ) %>%   
  separate(file_id, into = c("arm", "subject_id"), sep = "_") %>% 
  mutate(arm = recode(arm , "con" = "control", "exp" = "experimental"),
         subject_id = as.factor(subject_id),
         arm = as.factor(arm)) %>% 
  select(subject_id, arm, everything())

## Make a spaghetti plot showing observations on each subject over time, and comment on differences between groups.

tidy_data %>% 
  ggplot(aes(x = week, y = observations, group = subject_id)) +
  geom_line(aes(color = subject_id)) +
  facet_grid( . ~ arm) +
  labs(
    title = " Spaghetti Plot showing Observations on Each Subject Over Time,  ",
    x = "Week",
    y = " Weekly Observations"
  )

```
Interpretation: 
Based on the plot above, we can see that on average that as time went by, the weekly observation is relative stable in control group. On the contrary, there was a increasing trend in weekly observation in experimental group. Overall, experimental group showed larger observation than control group.

